http://localhost:3000/weather/5-day
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJlbnMuamFzcGVyc0BnbWFpbC5jb20iLCJpZCI6Niwicm9sZXMiOlsiYWRtaW4iLCJtZW1iZXIiXSwiaWF0IjoxNTgzNjgwMjA3LCJleHAiOjE1ODM2ODM4MDd9.dp6YzMOK4qxodLMiLfi72kRxzNgCQ17-Wf9qcdwBheU